// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test, console2, Vm} from "forge-std/Test.sol";
import {Deployers} from "@uniswap/v4-core/test/utils/Deployers.sol";
import {Hooks} from "@uniswap/v4-core/src/libraries/Hooks.sol";
import {IHooks} from "@uniswap/v4-core/src/interfaces/IHooks.sol";
import {IPoolManager} from "@uniswap/v4-core/src/interfaces/IPoolManager.sol";
import {PoolKey} from "@uniswap/v4-core/src/types/PoolKey.sol";
import {PoolId, PoolIdLibrary} from "@uniswap/v4-core/src/types/PoolId.sol";
import {LPFeeLibrary} from "@uniswap/v4-core/src/libraries/LPFeeLibrary.sol";
import {Currency} from "@uniswap/v4-core/src/types/Currency.sol";
import {SwapParams, ModifyLiquidityParams} from "@uniswap/v4-core/src/types/PoolOperation.sol";
import {PoolSwapTest} from "@uniswap/v4-core/src/test/PoolSwapTest.sol";
import {MockERC20} from "solmate/src/test/utils/mocks/MockERC20.sol";
import {HookMiner} from "@uniswap/v4-periphery/src/utils/HookMiner.sol";
import {CustomRevert} from "@uniswap/v4-core/src/libraries/CustomRevert.sol";
import {BN254Lib} from "../src/libraries/BN254Lib.sol";

import {GradientShieldHook} from "../src/GradientShieldHook.sol";
import {ScoringOracle} from "../src/ScoringOracle.sol";
import {IScoreTaskCreator} from "../src/IScoreTaskCreator.sol";
import {BLSQuorumTaskManager} from "../src/BLSQuorumTaskManager.sol";

/// @title BLS Quorum Integration
/// @notice End-to-end AVS loop with REAL BN254 BLS aggregate signatures:
///
///   sandwich on-chain → hook auto-creates task → operators sign in G1 →
///   aggregator submits → pairing precompile verifies → oracle score written →
///   next swap prices off the new score → repeat offender rejected.
///
/// No mocks, no overridden verification: every signature in this file is a real
/// BLS signature checked by the EVM's pairing precompile.
///
/// Keys generated by `node operator/blsKeygen.js --solidity`.
contract BLSQuorumIntegrationTest is Test, Deployers {
    using PoolIdLibrary for PoolKey;
    using BN254Lib for BN254Lib.G1Point;

    GradientShieldHook internal hook;
    ScoringOracle internal oracle;
    BLSQuorumTaskManager internal tm;

    PoolSwapTest internal botRouter;
    PoolSwapTest internal victimRouter;

    address internal aggregator = address(0xA66);
    address internal generator = address(0x6E11);

    address internal bot = address(0xB07);
    address internal victim = address(0xA01);

    address[3] internal operators = [address(0x09E1), address(0x09E2), address(0x09E3)];

    // ---- BLS keys: generated by operator/blsKeygen.js --solidity ----

    uint256 internal constant SK0 =
        11836524677592296387016191132851638603374790022583809656474156559297518898960;
    uint256 internal constant SK1 =
        19555997293406794063693177147922824186012332787252529891418736435524183332599;
    uint256 internal constant SK2 =
        5387227035703601869654588749405678853951065557445841164820569872053046802407;

    function pkG2_0() internal pure returns (BN254Lib.G2Point memory) {
        return BN254Lib.G2Point({
            X: [
                uint256(856235766871160934255119714976447225765094315225094093722296097621447953790),
                10504330524665265161487698851180383364258894789243439674411633590019012327578
            ],
            Y: [
                uint256(3666150365687673034263234970711717605532414595737092948735142721639156450141),
                3304877456389278212911144062620124687525125721989181796243368116323056933776
            ]
        });
    }

    function pkG2_1() internal pure returns (BN254Lib.G2Point memory) {
        return BN254Lib.G2Point({
            X: [
                uint256(6925250543173333900918339604601365821001698015008601407643477466524441393506),
                6013106775456218963000217368193289349832165727925450983529809427298369235782
            ],
            Y: [
                uint256(21884788739770288123910103937511194363943440813944999666818587164189937001049),
                7404460905394065203237075113841088442937590790740222089454972653390615679657
            ]
        });
    }

    function pkG2_2() internal pure returns (BN254Lib.G2Point memory) {
        return BN254Lib.G2Point({
            X: [
                uint256(10232681038361472899206715458036792605758577938341181091810178331886553019652),
                18650162000802332061573029776033305850753403025274315343574234725455186114229
            ],
            Y: [
                uint256(16519535467380043117273924777006933058286580987918465947027655130114061783960),
                15733189498907505314869522439888592490841021188326098235011183020971275858591
            ]
        });
    }

    /// Aggregate G2 key for signers {0,1,2}. G2 addition has no EVM precompile,
    /// so aggregates are precomputed off-chain — exactly as a real aggregator does.
    function apkG2_All3() internal pure returns (BN254Lib.G2Point memory) {
        return BN254Lib.G2Point({
            X: [
                uint256(2840644583317869262398633998794092728062714745195347789655693215124596099039),
                7613008426637789760294252186863964027461017681846194833368190508380176611534
            ],
            Y: [
                uint256(11010470600951199211697531281820826206738753393686408421563789003927424186505),
                10444254178227287990843911155892801628184356026023855419141095646764940859503
            ]
        });
    }

    /// Aggregate G2 key for signers {0,1}.
    function apkG2_First2() internal pure returns (BN254Lib.G2Point memory) {
        return BN254Lib.G2Point({
            X: [
                uint256(17893237007145536954592889806467571901553555199057167520398058204904369149060),
                12297885063595889541228452148764789829336205176048302706525201359983951754985
            ],
            Y: [
                uint256(21818202474519982310384319866503611347553559630467044904841892990149710819067),
                1164509888561843959507299365287774311612264800489582549049509038088097948451
            ]
        });
    }

    // =====================================================================
    //  Setup
    // =====================================================================

    function setUp() public {
        vm.roll(100);

        deployFreshManagerAndRouters();

        // Oracle first; its AVS writer is the BLS task manager.
        oracle = new ScoringOracle(address(0));
        tm = new BLSQuorumTaskManager(oracle, aggregator, generator);
        oracle.setAvs(address(tm));

        uint160 flags = uint160(
            Hooks.BEFORE_SWAP_FLAG | Hooks.BEFORE_ADD_LIQUIDITY_FLAG | Hooks.BEFORE_REMOVE_LIQUIDITY_FLAG
        );
        (address hookAddr, bytes32 salt) = HookMiner.find(
            address(this),
            flags,
            type(GradientShieldHook).creationCode,
            abi.encode(manager, oracle, IScoreTaskCreator(address(tm)), address(0))
        );
        hook = new GradientShieldHook{salt: salt}(
            IPoolManager(manager), oracle, IScoreTaskCreator(address(tm)), address(0)
        );
        require(address(hook) == hookAddr, "hook address mismatch");

        tm.setHookAddress(address(hook));

        // Register the operator quorum with their real BLS keys.
        tm.registerOperator(operators[0], _pkG1(SK0), pkG2_0());
        tm.registerOperator(operators[1], _pkG1(SK1), pkG2_1());
        tm.registerOperator(operators[2], _pkG1(SK2), pkG2_2());

        _setUpPool();
    }

    function _setUpPool() internal {
        deployMintAndApprove2Currencies();
        MockERC20 t0 = MockERC20(Currency.unwrap(currency0));
        MockERC20 t1 = MockERC20(Currency.unwrap(currency1));

        botRouter = new PoolSwapTest(manager);
        victimRouter = new PoolSwapTest(manager);

        address[2] memory actors = [bot, victim];
        PoolSwapTest[2] memory routers = [botRouter, victimRouter];
        for (uint256 i = 0; i < 2; i++) {
            t0.mint(actors[i], 1000 ether);
            t1.mint(actors[i], 1000 ether);
            vm.startPrank(actors[i]);
            t0.approve(address(routers[i]), type(uint256).max);
            t1.approve(address(routers[i]), type(uint256).max);
            vm.stopPrank();
        }

        (key,) = initPoolAndAddLiquidity(
            currency0, currency1, IHooks(address(hook)), LPFeeLibrary.DYNAMIC_FEE_FLAG, SQRT_PRICE_1_1
        );

        t0.mint(address(this), 10_000 ether);
        t1.mint(address(this), 10_000 ether);
        t0.approve(address(modifyLiquidityRouter), type(uint256).max);
        t1.approve(address(modifyLiquidityRouter), type(uint256).max);
        modifyLiquidityRouter.modifyLiquidity(
            key,
            ModifyLiquidityParams({tickLower: -120, tickUpper: 120, liquidityDelta: 100_000 ether, salt: bytes32(0)}),
            ZERO_BYTES
        );
    }

    // =====================================================================
    //  THE FULL LOOP
    // =====================================================================

    function test_fullLoop_sandwichToBLSQuorumToEscalatedFee() public {
        console2.log("");
        console2.log("=========================================================");
        console2.log(" GRADIENTSHIELD AVS LOOP - REAL BLS QUORUM");
        console2.log("=========================================================");
        console2.log("  Operators registered:", tm.operatorCount());

        // --- 1. Bot sandwiches a victim in one block ---
        console2.log("");
        console2.log("  [1] Bot sandwiches a victim (same block)");
        _swap(botRouter, true, -1 ether); // front-run
        _swap(victimRouter, true, -1 ether); // victim

        vm.recordLogs();
        _swap(botRouter, false, -1 ether); // back-run

        (bool detected, bool taskMade) = _sawDetectionAndTask(vm.getRecordedLogs());
        assertTrue(detected, "hook should detect the sandwich");
        assertTrue(taskMade, "hook should auto-create a scoring task");
        console2.log("      SandwichDetected + ScoreTaskCreated emitted");

        uint32 taskIndex = tm.latestTaskForSubject(bot);
        console2.log("      Task index:", taskIndex);

        // --- 2. Operators independently sign the verdict ---
        uint16 verdict = 60;
        bytes32 msgHash = tm.scoreMessageHash(taskIndex, bot, verdict);
        console2.log("");
        console2.log("  [2] 3 operators sign score=60 with their BLS keys");

        BN254Lib.G1Point memory sigma = _aggregateSign3(msgHash);
        console2.log("      Aggregate signature computed (G1 point sum)");

        // --- 3. Aggregator submits; the pairing precompile verifies ---
        console2.log("");
        console2.log("  [3] Aggregator submits to BLSQuorumTaskManager");
        assertEq(oracle.getScore(bot), 0, "score starts clean");

        uint256[] memory signers = _signers3();
        vm.prank(aggregator);
        tm.respondToScoreTask(taskIndex, verdict, signers, apkG2_All3(), sigma);

        assertEq(oracle.getScore(bot), 60, "BLS quorum wrote the score");
        console2.log("      BLS pairing VERIFIED - oracle score now:", oracle.getScore(bot));

        // --- 4. The bot's next swap is priced off the quorum verdict ---
        console2.log("");
        console2.log("  [4] Bot's next swap is repriced by the hook");
        vm.roll(block.number + 1);

        vm.recordLogs();
        _swap(botRouter, true, -1 ether);

        uint24 charged = _feeFromTelemetry(vm.getRecordedLogs());
        // Continuous curve at score 60: 3000 + 12000 * 20/40 = 9000
        assertEq(charged, 9000, "score 60 maps to 0.90%");
        console2.log("      Fee charged:", charged, "pips (0.90% vs 0.30% base)");

        // --- 5. Repeat offence escalates past the reject threshold ---
        console2.log("");
        console2.log("  [5] Bot reoffends; quorum raises the score to 85");
        vm.roll(block.number + 1);
        _createTaskAsGenerator(bot, 67);

        uint32 t2 = tm.latestTaskForSubject(bot);
        BN254Lib.G1Point memory sigma2 = _aggregateSign3(tm.scoreMessageHash(t2, bot, 85));

        vm.prank(aggregator);
        tm.respondToScoreTask(t2, 85, _signers3(), apkG2_All3(), sigma2);
        assertEq(oracle.getScore(bot), 85);

        vm.roll(block.number + 1);
        vm.expectRevert(
            abi.encodeWithSelector(
                CustomRevert.WrappedError.selector,
                address(hook),
                IHooks.beforeSwap.selector,
                abi.encodeWithSelector(GradientShieldHook.BotRejected.selector, bot, uint16(85)),
                abi.encodeWithSelector(Hooks.HookCallFailed.selector)
            )
        );
        _swap(botRouter, true, -1 ether);
        console2.log("      Swap REJECTED - bot is priced out of the pool");
        console2.log("");
        console2.log("=========================================================");
    }

    // =====================================================================
    //  BLS VERIFICATION PROPERTIES
    // =====================================================================

    function test_bls_validAggregateSignatureVerifies() public view {
        bytes32 msgHash = tm.scoreMessageHash(0, bot, 55);
        BN254Lib.G1Point memory sigma = _aggregateSign3(msgHash);
        BN254Lib.G1Point memory apkG1 = _aggregatePk3();

        (bool pairingOk, bool sigOk) = tm.verifySignature(msgHash, apkG1, apkG2_All3(), sigma);
        assertTrue(pairingOk, "pairing should succeed");
        assertTrue(sigOk, "aggregate signature should be valid");
    }

    function test_bls_signatureOverDifferentScoreIsRejected() public {
        uint32 taskIndex = _createTaskAsGenerator(bot, 67);

        // Operators sign score=60 but the aggregator submits score=10.
        BN254Lib.G1Point memory sigma = _aggregateSign3(tm.scoreMessageHash(taskIndex, bot, 60));

        vm.prank(aggregator);
        vm.expectRevert(BLSQuorumTaskManager.InvalidBLSSignature.selector);
        tm.respondToScoreTask(taskIndex, 10, _signers3(), apkG2_All3(), sigma);
    }

    function test_bls_wrongAggregatePubkeyIsRejected() public {
        uint32 taskIndex = _createTaskAsGenerator(bot, 67);
        BN254Lib.G1Point memory sigma = _aggregateSign3(tm.scoreMessageHash(taskIndex, bot, 60));

        // All 3 signed, but the aggregator supplies the 2-signer apkG2.
        vm.prank(aggregator);
        vm.expectRevert(BLSQuorumTaskManager.InvalidBLSSignature.selector);
        tm.respondToScoreTask(taskIndex, 60, _signers3(), apkG2_First2(), sigma);
    }

    function test_bls_forgedSignatureIsRejected() public {
        uint32 taskIndex = _createTaskAsGenerator(bot, 67);

        // An attacker without the keys cannot fabricate a valid G1 point.
        BN254Lib.G1Point memory forged = BN254Lib.generatorG1().scalar_mul(123456789);

        vm.prank(aggregator);
        vm.expectRevert(BLSQuorumTaskManager.InvalidBLSSignature.selector);
        tm.respondToScoreTask(taskIndex, 60, _signers3(), apkG2_All3(), forged);
    }

    // =====================================================================
    //  QUORUM THRESHOLD
    // =====================================================================

    function test_quorum_twoOfThreeMeetsSixtyPercent() public {
        // 2/3 = 66.6% >= 60% → accepted.
        uint32 taskIndex = _createTaskAsGenerator(bot, 60);

        bytes32 msgHash = tm.scoreMessageHash(taskIndex, bot, 45);
        BN254Lib.G1Point memory sigma = _sign(SK0, msgHash).plus(_sign(SK1, msgHash));

        uint256[] memory signers = new uint256[](2);
        signers[0] = 0;
        signers[1] = 1;

        vm.prank(aggregator);
        tm.respondToScoreTask(taskIndex, 45, signers, apkG2_First2(), sigma);

        assertEq(oracle.getScore(bot), 45, "2-of-3 met the 60% threshold");
    }

    function test_quorum_twoOfThreeFailsSixtySevenPercent() public {
        // 2/3 = 66.6% < 67% → rejected before any pairing work.
        uint32 taskIndex = _createTaskAsGenerator(bot, 67);

        bytes32 msgHash = tm.scoreMessageHash(taskIndex, bot, 45);
        BN254Lib.G1Point memory sigma = _sign(SK0, msgHash).plus(_sign(SK1, msgHash));

        uint256[] memory signers = new uint256[](2);
        signers[0] = 0;
        signers[1] = 1;

        vm.prank(aggregator);
        vm.expectRevert(abi.encodeWithSelector(BLSQuorumTaskManager.QuorumNotMet.selector, 2, 3));
        tm.respondToScoreTask(taskIndex, 45, signers, apkG2_First2(), sigma);

        assertEq(oracle.getScore(bot), 0, "score unchanged when quorum fails");
    }

    function test_quorum_duplicateSignersRejected() public {
        // Replaying one operator to fake a quorum must not work.
        uint32 taskIndex = _createTaskAsGenerator(bot, 67);

        bytes32 msgHash = tm.scoreMessageHash(taskIndex, bot, 45);
        BN254Lib.G1Point memory sigma = _sign(SK0, msgHash);

        uint256[] memory signers = new uint256[](3);
        signers[0] = 0;
        signers[1] = 0;
        signers[2] = 0;

        vm.prank(aggregator);
        vm.expectRevert(BLSQuorumTaskManager.SignersNotSorted.selector);
        tm.respondToScoreTask(taskIndex, 45, signers, apkG2_All3(), sigma);
    }

    // =====================================================================
    //  ACCESS CONTROL / LIFECYCLE
    // =====================================================================

    function test_access_onlyAggregatorCanRespond() public {
        uint32 taskIndex = _createTaskAsGenerator(bot, 67);
        BN254Lib.G1Point memory sigma = _aggregateSign3(tm.scoreMessageHash(taskIndex, bot, 60));

        vm.prank(address(0xBAD));
        vm.expectRevert(BLSQuorumTaskManager.NotAggregator.selector);
        tm.respondToScoreTask(taskIndex, 60, _signers3(), apkG2_All3(), sigma);
    }

    function test_access_onlyHookOrGeneratorCanCreateTask() public {
        vm.prank(address(0xBAD));
        vm.expectRevert(BLSQuorumTaskManager.NotTaskCreator.selector);
        tm.createScoreTask(bot, 0, block.number, 67, hex"00");
    }

    function test_lifecycle_taskCannotBeAnsweredTwice() public {
        uint32 taskIndex = _createTaskAsGenerator(bot, 67);
        BN254Lib.G1Point memory sigma = _aggregateSign3(tm.scoreMessageHash(taskIndex, bot, 60));

        vm.prank(aggregator);
        tm.respondToScoreTask(taskIndex, 60, _signers3(), apkG2_All3(), sigma);

        vm.prank(aggregator);
        vm.expectRevert(BLSQuorumTaskManager.TaskAlreadyResponded.selector);
        tm.respondToScoreTask(taskIndex, 60, _signers3(), apkG2_All3(), sigma);
    }

    function test_lifecycle_responseWindowExpires() public {
        uint32 taskIndex = _createTaskAsGenerator(bot, 67);
        BN254Lib.G1Point memory sigma = _aggregateSign3(tm.scoreMessageHash(taskIndex, bot, 60));

        vm.roll(block.number + tm.TASK_RESPONSE_WINDOW_BLOCK() + 1);

        vm.prank(aggregator);
        vm.expectRevert(BLSQuorumTaskManager.ResponseTooLate.selector);
        tm.respondToScoreTask(taskIndex, 60, _signers3(), apkG2_All3(), sigma);
    }

    function test_registry_deregisterShrinksQuorum() public {
        assertEq(tm.operatorCount(), 3);
        tm.deregisterOperator(operators[2]);
        assertEq(tm.operatorCount(), 2);
    }

    // =====================================================================
    //  Helpers — BLS signing done with the EVM's own G1 precompiles
    // =====================================================================

    /// pkG1 = sk · G1
    function _pkG1(uint256 sk) internal view returns (BN254Lib.G1Point memory) {
        return BN254Lib.generatorG1().scalar_mul(sk);
    }

    /// sigma = sk · H(msg)
    function _sign(uint256 sk, bytes32 msgHash) internal view returns (BN254Lib.G1Point memory) {
        return BN254Lib.hashToG1(msgHash).scalar_mul(sk);
    }

    function _aggregateSign3(bytes32 msgHash) internal view returns (BN254Lib.G1Point memory) {
        return _sign(SK0, msgHash).plus(_sign(SK1, msgHash)).plus(_sign(SK2, msgHash));
    }

    function _aggregatePk3() internal view returns (BN254Lib.G1Point memory) {
        return _pkG1(SK0).plus(_pkG1(SK1)).plus(_pkG1(SK2));
    }

    function _signers3() internal pure returns (uint256[] memory s) {
        s = new uint256[](3);
        s[0] = 0;
        s[1] = 1;
        s[2] = 2;
    }

    function _createTaskAsGenerator(address subject, uint32 threshold) internal returns (uint32) {
        vm.prank(generator);
        tm.createScoreTask(subject, block.number, block.number, threshold, hex"00");
        return tm.latestTaskForSubject(subject);
    }

    // ---- log helpers ----

    function _sawDetectionAndTask(Vm.Log[] memory logs) internal pure returns (bool detected, bool taskMade) {
        bytes32 sandwichSig = keccak256("SandwichDetected(bytes32,address,uint256)");
        bytes32 taskSig = keccak256("ScoreTaskCreated(uint32,address,uint256,uint256,uint32)");
        for (uint256 i = 0; i < logs.length; i++) {
            if (logs[i].topics[0] == sandwichSig) detected = true;
            if (logs[i].topics[0] == taskSig) taskMade = true;
        }
    }

    function _feeFromTelemetry(Vm.Log[] memory logs) internal pure returns (uint24 fee) {
        bytes32 sig = keccak256("SwapTelemetry(bytes32,address,bool,int256,uint16,uint24,uint256)");
        for (uint256 i = 0; i < logs.length; i++) {
            if (logs[i].topics[0] == sig) {
                (,,, uint24 charged,) = abi.decode(logs[i].data, (bool, int256, uint16, uint24, uint256));
                fee = charged;
            }
        }
    }

    /// @dev The actor must be pranked so the router pulls tokens from them.
    ///      Note the hook still identifies the swapper as the *router* — see
    ///      the identity caveat in the README.
    function _swap(PoolSwapTest router, bool zeroForOne, int256 amount) internal {
        // Two-arg prank sets tx.origin, so the hook resolves each actor as a
        // distinct trader rather than collapsing them into the router.
        address actor = router == botRouter ? bot : victim;
        vm.prank(actor, actor);
        router.swap(
            key,
            SwapParams({
                zeroForOne: zeroForOne,
                amountSpecified: amount,
                sqrtPriceLimitX96: zeroForOne ? MIN_PRICE_LIMIT : MAX_PRICE_LIMIT
            }),
            PoolSwapTest.TestSettings({takeClaims: false, settleUsingBurn: false}),
            ZERO_BYTES
        );
    }
}
