[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.27"
evm_version = "cancun"
optimizer = true
optimizer_runs = 800
via_ir = false
ffi = true                # required by HookMiner / CREATE2 address mining
fs_permissions = [{ access = "read-write", path = "./" }]

# See https://book.getfoundry.sh/reference/config/ for all options.

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
