// Generate BN254 BLS keypairs for the GradientShield operator quorum.
//
//   node blsKeygen.js            → keys.json for the runtime operator/aggregator
//   node blsKeygen.js --solidity → Solidity constants for the integration test
//
// Keys are derived deterministically from fixed seeds so the test fixtures and
// the local demo deployment always agree.

import { writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { derivePrivateKey, publicKeys, aggregateG2 } from "./bls.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Deterministic demo seeds. Real operators generate these privately.
const SEEDS = [
  "0x1a2b3c4d5e6f70819293a4b5c6d7e8f90102030405060708090a0b0c0d0e0f10",
  "0x2b3c4d5e6f708192a3b4c5d6e7f8091a020304050607080910111213141516f7",
  "0x3c4d5e6f708192a3b4c5d6e7f8091a2b0304050607080910111213141516f7e8",
];

const keys = SEEDS.map((seed, i) => {
  const sk = derivePrivateKey(seed);
  const k = publicKeys(sk);
  return { index: i, name: `operator${i}`, ...k };
});

function hex(v) {
  return "0x" + v.toString(16).padStart(64, "0");
}

if (process.argv.includes("--solidity")) {
  const g1 = (p) => `BN254.G1Point({X: ${p.X}, Y: ${p.Y}})`;
  const g2 = (p) =>
    `BN254.G2Point({X: [uint256(${p.X[0]}), ${p.X[1]}], Y: [uint256(${p.Y[0]}), ${p.Y[1]}]})`;

  console.log("// ---- generated by: node operator/blsKeygen.js --solidity ----");
  for (const k of keys) {
    console.log(`\n// operator ${k.index}`);
    console.log(`uint256 internal constant SK${k.index} = ${k.sk};`);
    console.log(`function pkG2_${k.index}() internal pure returns (BN254.G2Point memory) {`);
    console.log(`    return ${g2(k.pkG2)};`);
    console.log(`}`);
  }

  // Aggregate G2 keys for the signer subsets the test exercises.
  // G2 addition has no EVM precompile, so these must be precomputed.
  const subsets = [
    [[0, 1, 2], "All3"],
    [[0, 1], "First2"],
    [[0], "Only0"],
  ];
  for (const [idxs, label] of subsets) {
    const agg = aggregateG2(idxs.map((i) => keys[i].pkG2));
    console.log(`\n// aggregate G2 pubkey for signers {${idxs.join(", ")}}`);
    console.log(`function apkG2_${label}() internal pure returns (BN254.G2Point memory) {`);
    console.log(`    return ${g2(agg)};`);
    console.log(`}`);
  }
} else {
  const out = {
    note: "DEMO KEYS — deterministic and public. Never reuse for anything real.",
    operators: keys.map((k) => ({
      index: k.index,
      name: k.name,
      privateKey: hex(k.sk),
      pkG1: { X: hex(k.pkG1.X), Y: hex(k.pkG1.Y) },
      pkG2: {
        X: [hex(k.pkG2.X[0]), hex(k.pkG2.X[1])],
        Y: [hex(k.pkG2.Y[0]), hex(k.pkG2.Y[1])],
      },
    })),
  };
  const path = join(__dirname, "keys.json");
  writeFileSync(path, JSON.stringify(out, null, 2));
  console.log(`Wrote ${keys.length} BLS keypairs to ${path}`);
  for (const k of keys) {
    console.log(`  ${k.name}: pkG1.X = ${hex(k.pkG1.X).slice(0, 18)}…`);
  }
}
